= Connections
:imagesdir: ../assets/images

First, we have to define the connections the plugin uses to connect to the Cisco UCS Manager Super Visor. A connection consists of
a Username/Password with a URL to authenticate against the UCS Manager, and an alias used to reference it. Connections
are saved internally in the Secure Credentials Vault.

You can useKaraf shell commands to add, validate, and modify connections.

== Karaf
.Connect to Karaf shell.
[source, console]
----
ssh -p 8101 admin@localhost
----
[source, console]
.List existing connections.
----
admin@opennms()> opennms-cucs:connection-list --help
DESCRIPTION
        opennms-cucs:connection-list

	List existing connections

SYNTAX
        opennms-cucs:connection-list

DETAILS
        List all existing connections to orchestrators
----

[source, console]
.Get UCS Entity by DN for connection alias.
----
admin@opennms()> opennms-cucs:get-ucs-entity --help
DESCRIPTION
        opennms-cucs:get-ucs-entity

	Get Ucs Entity

SYNTAX
        opennms-cucs:get-ucs-entity alias dn

ARGUMENTS
        alias
                Connection alias
                (required)
        dn
                DN of the entity
                (required)

DETAILS
        Get Ucs Entity by Dn
 ----

[source, console]
.List Ucs Dn by classId.
----
admin@opennms()> opennms-cucs:list-ucs-dn-by-class --help
DESCRIPTION
        opennms-cucs:list-ucs-dn-by-class

	List Ucs Dn by classId

SYNTAX
        opennms-cucs:list-ucs-dn-by-class alias classId

ARGUMENTS
        alias
                Connection alias
                (required)
        classId
                classId
                (required)

DETAILS
        List all DN Item
----

[source, console]
.List all Supported Ucs Entity.
----
admin@opennms()> opennms-cucs:list-ucs-entity --help
DESCRIPTION
        opennms-cucs:list-ucs-entity

	List Ucs Entity

SYNTAX
        opennms-cucs:list-ucs-entity alias

ARGUMENTS
        alias
                Connection alias
                (required)

DETAILS
        List all Supported Ucs Entity
----

[source, console]
.Add a connection.
----
DESCRIPTION
        opennms-cucs:connection-add

	Add a connection

SYNTAX
        opennms-cucs:connection-add [options] alias url username password [validity]

ARGUMENTS
        alias
                Alias
                (required)
        url
                Cisco Ucs Manager XML API Url
                (required)
        username
                Cisco Ucs Manager XML API username
                (required)
        password
                Cisco Ucs Manager XML API password
                (required)
        validity
                Cisco Ucs Manager XML API time in seconds to refresh connection
                (defaults to 30)

OPTIONS
        --help
                Display this help message
        -t, --test
                Dry run mode, test the credentials but do not save them
        -f, --force
                Skip validation and save the connection as-is
        -i, --ignore-ssl-certificate-validation
                Ignore ssl certificate validation

DETAILS
        Add a connection of Cisco UCS Manager XML API
----

[source, console]
.Edit an existing connection.
----
admin@opennms()> opennms-cucs:connection-edit --help
DESCRIPTION
        opennms-cucs:connection-edit

	Edit a connection

SYNTAX
        opennms-cucs:connection-edit [options] alias url username password [validity]

ARGUMENTS
        alias
                Alias
                (required)
        url
               Cisco Ucs Manager XML API Url
                (required)
        username
                Cisco Ucs Manager XML API username
                (required)
        password
                Cisco Ucs Manager XML API password
                (required)
        validity
                Cisco Ucs Manager XML API time in seconds to refresh connection
                (defaults to 30)

OPTIONS
        --help
                Display this help message
        -f, --force
                Skip validation and save the connection as-is
        -i, --ignore-ssl-certificate-validation
                Ignore ssl certificate validation

DETAILS
        Edit an existing connection for Cisco UCS Manger XML API
----

[source, console]
.Validate an existing connection.
----
DESCRIPTION
        opennms-cucs:connection-validate

	Validate a connection

SYNTAX
        opennms-cucs:connection-validate alias

ARGUMENTS
        alias
                Alias
                (required)

DETAILS
        Validate an existing connection to a Cisco UCS Manager XML API
----

[source, console]
.Delete an existing connection.
----
DESCRIPTION
        opennms-cucs:connection-delete

	Delete a connection

SYNTAX
        opennms-cucs:connection-delete alias

ARGUMENTS
        alias
                Connection alias to delete
                (required)

DETAILS
        Deletes a connection for Cisco UCS Manager XML API
----
