package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class AdaptorVnicStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRx;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTx;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedRx;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedTx;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public int droppedTxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsRx;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsTx;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public int errorsTxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsRx;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsTx;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public int packetsTxDeltaMin;
}

