package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class AdaptorVnicStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRx;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTx;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long bytesTxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedRx;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedTx;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long droppedTxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsRx;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsTx;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long errorsTxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsRx;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsTx;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long packetsTxDeltaMin;
}

