package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class ComputePCIeFatalStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long acsViolationErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int acsViolationErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long malformedTLPErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int malformedTLPErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long poisonedTLPErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int poisonedTLPErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long surpriseLinkDownErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int surpriseLinkDownErrors2WeeksH;
}

