package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class ComputePCIeFatalReceiveStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long bufferOverflowErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int bufferOverflowErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long errFatalErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int errFatalErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long errNonFatalErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int errNonFatalErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long unsupportedRequestErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int unsupportedRequestErrors2WeeksH;
}

