package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class EtherLossStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long SQETest;
    @JacksonXmlProperty(isAttribute = true)
    public long SQETestDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long SQETestDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long SQETestDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long SQETestDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long carrierSense;
    @JacksonXmlProperty(isAttribute = true)
    public long carrierSenseDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long carrierSenseDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long carrierSenseDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long carrierSenseDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long excessCollision;
    @JacksonXmlProperty(isAttribute = true)
    public long excessCollisionDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long excessCollisionDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long excessCollisionDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long excessCollisionDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long giants;
    @JacksonXmlProperty(isAttribute = true)
    public long giantsDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long giantsDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long giantsDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long giantsDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long lateCollision;
    @JacksonXmlProperty(isAttribute = true)
    public long lateCollisionDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long lateCollisionDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long lateCollisionDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long lateCollisionDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long multiCollision;
    @JacksonXmlProperty(isAttribute = true)
    public long multiCollisionDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long multiCollisionDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long multiCollisionDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long multiCollisionDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long singleCollision;
    @JacksonXmlProperty(isAttribute = true)
    public long singleCollisionDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long singleCollisionDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long singleCollisionDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long singleCollisionDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long symbol;
    @JacksonXmlProperty(isAttribute = true)
    public long symbolDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long symbolDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long symbolDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long symbolDeltaMin;
}

