package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class FcErrStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long crcRx;
    @JacksonXmlProperty(isAttribute = true)
    public long crcRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long crcRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long crcRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long crcRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long discardRx;
    @JacksonXmlProperty(isAttribute = true)
    public long discardRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long discardRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long discardRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long discardRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long discardTx;
    @JacksonXmlProperty(isAttribute = true)
    public long discardTxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long discardTxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long discardTxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long discardTxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long linkFailures;
    @JacksonXmlProperty(isAttribute = true)
    public long linkFailuresDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long linkFailuresDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long linkFailuresDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long linkFailuresDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long rx;
    @JacksonXmlProperty(isAttribute = true)
    public long rxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long rxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long rxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long rxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long signalLosses;
    @JacksonXmlProperty(isAttribute = true)
    public long signalLossesDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long signalLossesDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long signalLossesDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long signalLossesDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long syncLosses;
    @JacksonXmlProperty(isAttribute = true)
    public long syncLossesDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long syncLossesDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long syncLossesDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long syncLossesDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long tooLongRx;
    @JacksonXmlProperty(isAttribute = true)
    public long tooLongRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long tooLongRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long tooLongRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long tooLongRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long tooShortRx;
    @JacksonXmlProperty(isAttribute = true)
    public long tooShortRxDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long tooShortRxDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long tooShortRxDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long tooShortRxDeltaMin;
    @JacksonXmlProperty(isAttribute = true)
    public long tx;
    @JacksonXmlProperty(isAttribute = true)
    public long txDelta;
    @JacksonXmlProperty(isAttribute = true)
    public long txDeltaAvg;
    @JacksonXmlProperty(isAttribute = true)
    public long txDeltaMax;
    @JacksonXmlProperty(isAttribute = true)
    public long txDeltaMin;
}

