package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class MemoryErrorStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long DramWriteDataCorrectableCRCErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataCorrectableCRCErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long DramWriteDataUnCorrectableCRCErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int DramWriteDataUnCorrectableCRCErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long addressParityErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long addressParityErrorsCorrectable;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsCorrectable2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long addressParityErrorsUnCorrectable;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int addressParityErrorsUnCorrectable2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long eccMultibitErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int eccMultibitErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long eccSinglebitErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int eccSinglebitErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long mismatchErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int mismatchErrors2WeeksH;
}

