package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class ProcessorErrorStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int CorrectableLinkCRCErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int UncorrectableLinkCRCErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringInterSockErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int mirroringIntraSockErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkCorrErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int smiLinkUncorrErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public int sparingErrors2WeeksH;
}

