package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class ProcessorErrorStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public long CorrectableLinkCRCErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public long UncorrectableLinkCRCErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringInterSockErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public long mirroringIntraSockErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkCorrErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public long smiLinkUncorrErrors2WeeksH;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors15Min;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors15MinH;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors1Day;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors1DayH;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors1Hour;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors1HourH;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors1Week;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors1WeekH;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors2Weeks;
    @JacksonXmlProperty(isAttribute = true)
    public long sparingErrors2WeeksH;
}

