package it.xeniaprogetti.cisco.ucs.plugin.client.impl.model.stats;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

public class SwEnvStats extends Stats {
    @JacksonXmlProperty(isAttribute = true)
    public String donner;
    @JacksonXmlProperty(isAttribute = true)
    public String donnerAvg;
    @JacksonXmlProperty(isAttribute = true)
    public String donnerMax;
    @JacksonXmlProperty(isAttribute = true)
    public String donnerMin;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet1;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet1Avg;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet1Max;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet1Min;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet2;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet2Avg;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet2Max;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet2Min;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet3;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet3Avg;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet3Max;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet3Min;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet4;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet4Avg;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet4Max;
    @JacksonXmlProperty(isAttribute = true)
    public String fanCtrlrInlet4Min;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet1;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet1Avg;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet1Max;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet1Min;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet2;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet2Avg;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet2Max;
    @JacksonXmlProperty(isAttribute = true)
    public double mainBoardOutlet2Min;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet1;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet1Avg;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet1Max;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet1Min;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet2;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet2Avg;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet2Max;
    @JacksonXmlProperty(isAttribute = true)
    public String psuCtrlrInlet2Min;
    @JacksonXmlProperty(isAttribute = true)
    public String td2;
    @JacksonXmlProperty(isAttribute = true)
    public String td2Avg;
    @JacksonXmlProperty(isAttribute = true)
    public String td2Max;
    @JacksonXmlProperty(isAttribute = true)
    public String td2Min;
    @JacksonXmlProperty(isAttribute = true)
    public String tiburon;
    @JacksonXmlProperty(isAttribute = true)
    public String tiburonAvg;
    @JacksonXmlProperty(isAttribute = true)
    public String tiburonMax;
    @JacksonXmlProperty(isAttribute = true)
    public String tiburonMin;
}

